// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI / Migrate connection (prisma db push, migrate). Use the DIRECT
    // (non-pooled) URL for DDL — Supabase port 5432 — falling back to
    // DATABASE_URL. The app runtime connects via the driver adapter in
    // src/lib/db.ts using the pooled DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"] ?? "",
  },
});
