import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { PrintFrame } from "@/components/print/print-frame";
import { DocHeader, DocTable } from "@/components/print/doc-parts";
import { runReport, REPORT_CATALOG } from "@/lib/services/reports";
import { runCustomReport } from "@/lib/services/report-builder";

export const dynamic = "force-dynamic";

function pick(
  sp: Record<string, string | string[] | undefined>,
  key: string
): string {
  const v = sp[key];
  return Array.isArray(v) ? v[0] || "" : v || "";
}
function pickAll(
  sp: Record<string, string | string[] | undefined>,
  key: string
): string[] {
  const v = sp[key];
  return Array.isArray(v) ? v : v ? [v] : [];
}

export default async function PrintReportPage({
  searchParams,
}: {
  searchParams?: Promise<Record<string, string | string[] | undefined>>;
}) {
  const sp = searchParams ? await searchParams : {};
  const key = pick(sp, "key");
  const entity = pick(sp, "entity");
  const company = await prisma.companySettings.findUnique({
    where: { id: "default" },
  });

  let table: { title: string; columns: string[]; rows: (string | number)[][] };
  let numericCols: boolean[] = [];

  if (entity) {
    const custom = await runCustomReport({
      entity,
      cols: pickAll(sp, "cols"),
      status: pick(sp, "status") || undefined,
      from: pick(sp, "from") || undefined,
      to: pick(sp, "to") || undefined,
      sort: pick(sp, "sort") || undefined,
      dir: pick(sp, "dir") === "desc" ? "desc" : "asc",
    }).catch(() => null);
    if (!custom) notFound();
    table = custom;
    numericCols = custom.colDefs.map((c) => !!c.numeric);
  } else {
    const known = REPORT_CATALOG.find((r) => r.key === key);
    if (!known) notFound();
    table = await runReport(key);
    numericCols = table.columns.map(
      (c) =>
        /amount|value|qty|hours|total|cost|balance|ppm|score|days/i.test(c)
    );
  }

  return (
    <PrintFrame>
      <DocHeader
        company={company?.name || "ForgeRP"}
        tagline={company?.tagline}
        title="Report"
        number={table.title}
        meta={[
          { label: "Generated", value: new Date().toISOString().slice(0, 10) },
          { label: "Rows", value: String(table.rows.length) },
        ]}
      />
      <DocTable
        columns={table.columns}
        rows={table.rows}
        align={numericCols.map((n) => (n ? "r" : ""))}
      />
      <p className="mt-6 text-[10px] text-neutral-400">
        Generated by ForgeRP · live data at time of print
      </p>
    </PrintFrame>
  );
}
